# Generated by Django 4.2.23 on 2025-07-31 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="nama kategori"),
                ),
                ("description", models.TextField(blank=True, verbose_name="deskripsi")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
            ],
            options={
                "verbose_name": "kategori",
                "verbose_name_plural": "kategori",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="nama pelanggan"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="telepon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="alamat")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
            ],
            options={
                "verbose_name": "pelanggan",
                "verbose_name_plural": "pelanggan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nama produk")),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="barcode",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR code",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="harga beli"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="harga jual"
                    ),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="stok")),
                (
                    "min_stock",
                    models.PositiveIntegerField(default=5, verbose_name="stok minimum"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pcs", max_length=50, verbose_name="satuan"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="deskripsi")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="gambar",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "produk",
                "verbose_name_plural": "produk",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nomor faktur"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="tanggal pembelian",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total pembelian"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="jumlah dibayar"
                    ),
                ),
                (
                    "due_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="jumlah hutang"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Lunas"),
                            ("PARTIAL", "Sebagian"),
                            ("UNPAID", "Belum Dibayar"),
                        ],
                        default="UNPAID",
                        max_length=20,
                        verbose_name="status pembayaran",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="catatan")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dibuat oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "pembelian",
                "verbose_name_plural": "pembelian",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="nomor faktur",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="tanggal penjualan",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total penjualan"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="diskon",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="pajak"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="grand total"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Tunai"),
                            ("CARD", "Kartu"),
                            ("TRANSFER", "Transfer"),
                            ("QRIS", "QRIS"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="metode pembayaran",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Lunas"),
                            ("PARTIAL", "Sebagian"),
                            ("UNPAID", "Belum Dibayar"),
                        ],
                        default="PAID",
                        max_length=20,
                        verbose_name="status pembayaran",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="catatan")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dibuat oleh",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="inventory.customer",
                        verbose_name="pelanggan",
                    ),
                ),
            ],
            options={
                "verbose_name": "penjualan",
                "verbose_name_plural": "penjualan",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="nama supplier"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="kontak person"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="telepon")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("address", models.TextField(verbose_name="alamat")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="diperbarui pada"),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "supplier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("ADD", "Tambah"), ("SUBTRACT", "Kurang")],
                        max_length=20,
                        verbose_name="tipe penyesuaian",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="jumlah")),
                ("reason", models.TextField(verbose_name="alasan")),
                (
                    "adjusted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="disesuaikan pada"
                    ),
                ),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="disesuaikan oleh",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="inventory.product",
                        verbose_name="produk",
                    ),
                ),
            ],
            options={
                "verbose_name": "penyesuaian stok",
                "verbose_name_plural": "penyesuaian stok",
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="jumlah")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="harga satuan"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="diskon",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total harga"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="inventory.product",
                        verbose_name="produk",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.sale",
                        verbose_name="penjualan",
                    ),
                ),
            ],
            options={
                "verbose_name": "item penjualan",
                "verbose_name_plural": "item penjualan",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="jumlah")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="harga satuan"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total harga"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="inventory.product",
                        verbose_name="produk",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchase",
                        verbose_name="pembelian",
                    ),
                ),
            ],
            options={
                "verbose_name": "item pembelian",
                "verbose_name_plural": "item pembelian",
            },
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="inventory.supplier",
                verbose_name="supplier",
            ),
        ),
    ]
